import React, { useState, useEffect } from "react";
import { useSelector, useDispatch } from "react-redux";
import {
  setZoneManagement,
  setSelectedZone,
  setCircuits,
  setCircuitMapping,
  saveZoneCircuiting,
  saveZoneCircuitingSummary,
} from "../../redux/features/app/circuitingSlice";
import { saveZoneSummary } from "../../redux/features/app/circuitingSummarySlice";

const ZoneManagement = () => {
  const dispatch = useDispatch();
  const rooms = useSelector((state) => state.newRooms?.rooms || []);
  const zones = useSelector((state) => state.circuiting.zones);
  const selectedZone = useSelector((state) => state.circuiting.selectedZone);
  const circuits = useSelector((state) => state.circuiting.circuits);
  const circuitMapping = useSelector(
    (state) => state.circuiting.circuitMapping
  );
  const lightsByRoom = useSelector((state) => state.lighting.lightsByRoom);

  // Get zone management data (separate from circuiting zones)
  const zoneManagementData = useSelector(
    (state) => state.circuiting.zoneManagement || []
  );

  const [newZoneName, setNewZoneName] = useState("");
  const [editingZone, setEditingZone] = useState(null);
  const [editName, setEditName] = useState("");
  const [showRoomSelector, setShowRoomSelector] = useState(null); // zoneId for which to show room selector
  const [selectedRoomToAdd, setSelectedRoomToAdd] = useState("");

  // Don't auto-create zones from rooms - zones should be created manually
  // This ensures zones are proper organizational units, not individual rooms

  // Clear any existing auto-generated zones on component mount
  useEffect(() => {
    if (zoneManagementData.length > 0) {
      const hasAutoGeneratedZones = zoneManagementData.some(
        (zone) => zone.type === "auto-generated"
      );
      if (hasAutoGeneratedZones) {
        // Clear all auto-generated zones and start fresh
        const manualZones = zoneManagementData.filter(
          (zone) => zone.type === "manual"
        );
        dispatch(setZoneManagement(manualZones));

        // Also clear selected zone if it was auto-generated
        if (selectedZone && selectedZone.type === "auto-generated") {
          dispatch(setSelectedZone(null));
        }
      }
    }
  }, [zoneManagementData, selectedZone, dispatch]);

  // Clear any auto-generated zones on first load
  useEffect(() => {
    // This runs only once when component mounts
    const clearAutoGeneratedZones = () => {
      if (zoneManagementData.length > 0) {
        const autoGeneratedZones = zoneManagementData.filter(
          (zone) => zone.type === "auto-generated"
        );
        if (autoGeneratedZones.length > 0) {
          console.log(
            "🧹 Clearing auto-generated zones:",
            autoGeneratedZones.map((z) => z.name)
          );
          const manualZones = zoneManagementData.filter(
            (zone) => zone.type === "manual"
          );
          dispatch(setZoneManagement(manualZones));
        }
      }
    };

    clearAutoGeneratedZones();
  }, []); // Empty dependency array - runs only once

  const handleCreateZone = () => {
    if (newZoneName.trim()) {
      const newZone = {
        id: `zone-${Date.now()}`,
        name: newZoneName.trim(),
        rooms: [],
        type: "manual",
      };
      dispatch(setZoneManagement([...zoneManagementData, newZone]));
      setNewZoneName("");
    }
  };

  const handleClearAllZones = () => {
    if (
      window.confirm(
        "Are you sure you want to clear all zones? This will remove all zone configurations and room assignments. This action cannot be undone."
      )
    ) {
      dispatch(setZoneManagement([]));
      if (selectedZone) {
        dispatch(setSelectedZone(null));
      }
    }
  };

  const handleDeleteZone = (zoneId) => {
    const updatedZones = zoneManagementData.filter(
      (zone) => zone.id !== zoneId
    );
    dispatch(setZoneManagement(updatedZones));

    // Clear selection if deleted zone was selected
    if (selectedZone && selectedZone.id === zoneId) {
      dispatch(setSelectedZone(null));
    }
  };

  const handleEditZone = (zone) => {
    setEditingZone(zone);
    setEditName(zone.name);
  };

  const handleSaveEdit = () => {
    if (editName.trim() && editingZone) {
      const updatedZones = zoneManagementData.map((zone) =>
        zone.id === editingZone.id ? { ...zone, name: editName.trim() } : zone
      );
      dispatch(setZoneManagement(updatedZones));

      // Update selected zone if it was the one being edited
      if (selectedZone && selectedZone.id === editingZone.id) {
        dispatch(setSelectedZone({ ...selectedZone, name: editName.trim() }));
      }

      setEditingZone(null);
      setEditName("");
    }
  };

  const handleCancelEdit = () => {
    setEditingZone(null);
    setEditName("");
  };

  const handleSelectZone = (zone) => {
    // If there's a previously selected zone with circuits, save its summary first
    if (selectedZone && Object.keys(circuits).length > 0) {
      // Generate fixture labels for the previous zone before switching
      const previousZoneFixtures = Object.entries(lightsByRoom).reduce(
        (sum, [rid, data]) => {
          if (selectedZone.rooms.includes(rid)) {
            return sum + (data?.lights?.length || 0);
          }
          return sum;
        },
        0
      );

      const previousZoneLabels = [];
      for (let i = 0; i < previousZoneFixtures; i++) {
        const zoneMatch = selectedZone.id.match(/zone(\d+)/i);
        const zoneNumber = zoneMatch ? parseInt(zoneMatch[1]) : 1;
        const zoneIdentifier = `Z${zoneNumber}`;

        const circuitNumber = Math.floor(i / 12) + 1;
        const positionInCircuit = i % 12;
        const batchNumber = Math.floor(positionInCircuit / 3) + 1;
        const phaseIndex = positionInCircuit % 3;
        const phases = ["R", "Y", "B"];
        const phase = phases[phaseIndex];
        const phaseNum = 1;

        const label = `${zoneIdentifier}/C${circuitNumber}/${batchNumber}${phase}${phaseNum}`;
        previousZoneLabels.push(label);
      }

      // Save the previous zone's circuiting data to new zones structure
      dispatch(
        saveZoneCircuiting({
          zoneId: selectedZone.id,
          fixtures: Object.entries(lightsByRoom).reduce((acc, [rid, data]) => {
            if (selectedZone.rooms.includes(rid)) {
              return [...acc, ...(data?.lights || [])];
            }
            return acc;
          }, []),
          circuits: Object.values(circuits),
          labels: previousZoneLabels,
        })
      );

      // Also save to legacy summary structure for backward compatibility
      dispatch(
        saveZoneCircuitingSummary({
          zoneId: selectedZone.id,
          zoneName: selectedZone.name,
          fixturesCount: previousZoneFixtures,
          circuits: Object.values(circuits),
          labels: previousZoneLabels,
        })
      );

      // Save to permanent circuiting summary slice
      // Extract zone number for the summary key (e.g., "zone1" -> "Z1")
      const summaryZoneMatch = selectedZone.id.match(/zone(\d+)/i);
      const summaryZoneNumber = summaryZoneMatch
        ? parseInt(summaryZoneMatch[1])
        : 1;
      const summaryZoneId = `Z${summaryZoneNumber}`;

      dispatch(
        saveZoneSummary({
          zoneId: summaryZoneId,
          fixtures: previousZoneLabels,
        })
      );
    }

    // Clear current circuits and circuit mapping for the new zone
    dispatch(setCircuits({}));
    dispatch(setCircuitMapping({}));

    // Set the new zone
    dispatch(setSelectedZone(zone));
  };

  // Room management functions
  const handleAddRoomToZone = (zoneId) => {
    if (selectedRoomToAdd) {
      const updatedZones = zoneManagementData.map((zone) => {
        if (zone.id === zoneId && !zone.rooms.includes(selectedRoomToAdd)) {
          return { ...zone, rooms: [...zone.rooms, selectedRoomToAdd] };
        }
        return zone;
      });
      dispatch(setZoneManagement(updatedZones));

      // Update selected zone if it was the one being modified
      if (selectedZone && selectedZone.id === zoneId) {
        const updatedZone = updatedZones.find((z) => z.id === zoneId);
        dispatch(setSelectedZone(updatedZone));
      }

      setSelectedRoomToAdd("");
      setShowRoomSelector(null);
    }
  };

  const handleRemoveRoomFromZone = (zoneId, roomId) => {
    const updatedZones = zoneManagementData.map((zone) => {
      if (zone.id === zoneId) {
        return { ...zone, rooms: zone.rooms.filter((r) => r !== roomId) };
      }
      return zone;
    });
    dispatch(setZoneManagement(updatedZones));

    // Update selected zone if it was the one being modified
    if (selectedZone && selectedZone.id === zoneId) {
      const updatedZone = updatedZones.find((z) => z.id === zoneId);
      dispatch(setSelectedZone(updatedZone));
    }
  };

  // Get available rooms for a zone (rooms not already in the zone)
  const getAvailableRooms = (zoneId) => {
    const zone = zoneManagementData.find((z) => z.id === zoneId);
    if (!zone) return rooms;
    
    // Filter out rooms already in the zone and remove duplicates based on room.id
    const availableRooms = rooms.filter((room) => !zone.rooms.includes(room.id));
    
    // Remove duplicates by keeping only the first occurrence of each room.id
    const uniqueRooms = availableRooms.filter((room, index, self) => 
      index === self.findIndex(r => r.id === room.id)
    );
    
    return uniqueRooms;
  };

  // Get room name by ID
  const getRoomName = (roomId) => {
    const room = rooms.find((r) => r.id === roomId);
    return room ? room.name || `Room ${roomId}` : `Room ${roomId}`;
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h4 className="text-sm font-medium text-gray-700">Zone Management</h4>
        <div className="flex items-center gap-2">
          <span className="text-xs text-gray-500">
            {zoneManagementData.length} zones
          </span>
          {zoneManagementData.length > 0 && (
            <button
              onClick={handleClearAllZones}
              className="px-2 py-1 text-xs bg-red-100 hover:bg-red-200 text-red-700 rounded border border-red-300 transition-colors"
              title="Clear all zones"
            >
              Clear All
            </button>
          )}
        </div>
      </div>

      <div className="flex gap-2">
        <input
          type="text"
          value={newZoneName}
          onChange={(e) => setNewZoneName(e.target.value)}
          placeholder="Enter zone name (e.g., Ground Floor)"
          className="flex-1 px-3 py-2 text-sm border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
        />
        <button
          onClick={handleCreateZone}
          disabled={!newZoneName.trim()}
          className="px-4 py-2 text-sm bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:bg-gray-300 disabled:cursor-not-allowed"
        >
          Create Zone
        </button>
      </div>

      {/* Zones List */}
      <div className="space-y-3 max-h-96 overflow-y-auto">
        {zoneManagementData.map((zone) => (
          <div
            key={zone.id}
            className={`p-4 border rounded-lg ${
              selectedZone?.id === zone.id
                ? "border-blue-500 bg-blue-50"
                : "border-gray-200 bg-white"
            }`}
          >
            {/* Zone Header */}
            <div className="flex items-center justify-between mb-3">
              <div className="flex-1">
                {editingZone?.id === zone.id ? (
                  <input
                    type="text"
                    value={editName}
                    onChange={(e) => setEditName(e.target.value)}
                    className="w-full px-2 py-1 text-sm border border-gray-300 rounded"
                    autoFocus
                  />
                ) : (
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-medium text-gray-900">
                      {zone.name}
                    </span>
                    <span className="text-xs text-gray-500">
                      ({zone.rooms.length} rooms)
                    </span>
                    {zone.type === "auto-generated" && (
                      <span className="text-xs bg-gray-100 text-gray-600 px-2 py-1 rounded">
                        Auto
                      </span>
                    )}
                  </div>
                )}
              </div>

              <div className="flex items-center gap-2">
                {editingZone?.id === zone.id ? (
                  <>
                    <button
                      onClick={handleSaveEdit}
                      className="text-xs text-green-600 hover:text-green-800"
                    >
                      Save
                    </button>
                    <button
                      onClick={handleCancelEdit}
                      className="text-xs text-gray-600 hover:text-gray-800"
                    >
                      Cancel
                    </button>
                  </>
                ) : (
                  <>
                    <button
                      onClick={() => handleSelectZone(zone)}
                      className={`text-xs px-2 py-1 rounded ${
                        selectedZone?.id === zone.id
                          ? "bg-blue-600 text-white"
                          : "bg-gray-100 text-gray-600 hover:bg-gray-200"
                      }`}
                    >
                      {selectedZone?.id === zone.id ? "Selected" : "Select"}
                    </button>
                    <button
                      onClick={() => handleEditZone(zone)}
                      className="text-xs text-blue-600 hover:text-blue-800"
                    >
                      Edit
                    </button>
                    {zone.type !== "auto-generated" && (
                      <button
                        onClick={() => handleDeleteZone(zone.id)}
                        className="text-xs text-red-600 hover:text-red-800"
                      >
                        Delete
                      </button>
                    )}
                  </>
                )}
              </div>
            </div>

            {/* Room Selection Section */}
            <div className="space-y-2">
              {/* Add Room Button */}
              <div className="flex gap-2">
                <button
                  onClick={() =>
                    setShowRoomSelector(
                      showRoomSelector === zone.id ? null : zone.id
                    )
                  }
                  className="text-xs px-3 py-1 bg-green-100 text-green-700 rounded hover:bg-green-200"
                >
                  {showRoomSelector === zone.id ? "Cancel" : "Add Room"}
                </button>
              </div>

              {/* Room Selection Dropdown */}
              {showRoomSelector === zone.id && (
                <div className="flex gap-2 p-2 bg-gray-50 rounded border">
                  <select
                    value={selectedRoomToAdd}
                    onChange={(e) => setSelectedRoomToAdd(e.target.value)}
                    className="flex-1 text-xs border border-gray-300 rounded px-2 py-1"
                  >
                    <option value="">Select a room...</option>
                    {getAvailableRooms(zone.id).map((room) => (
                      <option key={room.id} value={room.id}>
                        {room.name || `Room ${room.id}`}
                      </option>
                    ))}
                  </select>
                  <button
                    onClick={() => handleAddRoomToZone(zone.id)}
                    disabled={!selectedRoomToAdd}
                    className="text-xs px-3 py-1 bg-green-600 text-white rounded hover:bg-green-700 disabled:bg-gray-300"
                  >
                    Add
                  </button>
                </div>
              )}

              {/* Rooms List */}
              {zone.rooms.length > 0 && (
                <div className="space-y-1">
                  <div className="text-xs font-medium text-gray-600">
                    Rooms in this zone:
                  </div>
                  <div className="space-y-1">
                    {zone.rooms.map((roomId) => (
                      <div
                        key={roomId}
                        className="flex items-center justify-between p-2 bg-gray-50 rounded text-xs"
                      >
                        <span className="text-gray-700">
                          {getRoomName(roomId)}
                        </span>
                        <button
                          onClick={() =>
                            handleRemoveRoomFromZone(zone.id, roomId)
                          }
                          className="text-red-600 hover:text-red-800"
                        >
                          Remove
                        </button>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* No rooms message */}
              {zone.rooms.length === 0 && (
                <div className="text-xs text-gray-500 italic">
                  No rooms added to this zone yet
                </div>
              )}
            </div>
          </div>
        ))}
      </div>

      {zoneManagementData.length === 0 && (
        <div className="text-center py-4 text-gray-500">
          <p className="text-sm">No zones created yet</p>
          <p className="text-xs">
            Create a zone to start managing rooms and circuits
          </p>
          <div className="mt-2 p-2 bg-blue-50 border border-blue-200 rounded text-xs text-blue-700">
            <p>
              <strong>How to use:</strong>
            </p>
            <p>1. Create a zone (e.g., "Zone1", "Zone2")</p>
            <p>2. Add rooms to the zone</p>
            <p>3. Select the zone for circuiting</p>
          </div>
        </div>
      )}
    </div>
  );
};

export default ZoneManagement;
